### ISSUE TITLE
Cannot download data from zenodo

### ISSUE THREAD

**Issue by oguiza** [ChangWeiTan/TSRegression#12]
HI @ChangWeiTan,
First of all thanks for your work in putting together this repo and the regression datasets.
I don't know if this is the right place to report this issue but I cannot download the data using the zenodo links. If you go to any of the links in http://tseregression.org/ you get to the zenodo web where the download buttons are shown, but nothing happens when you press them. 
Could you please let me know if this is something you can fix or where should I log this issue?
Thanks!

**Comment by ChangWeiTan** [comment]
Hi, @oguiza 

It should work. Just tried to download it and it is still working. 

Are you clicking on the correct download button (see attached)?

![image](https://user-images.githubusercontent.com/570744/164344501-36f2f002-c507-4ec8-b7ee-6ed13afda1ca.png)

**Comment by oguiza** [comment]
Yes, I use that button.
The issue is that quite often you can't download anything. But it's not always. I don't know if the issue occurs with Monash data only or with zenodo in general.
