### ISSUE TITLE
Consider documenting the dependencies

### ISSUE THREAD

**Issue by lemire** [ChangWeiTan/TSRegression#2]
At least pandas and sklearn are required. It should be covered in the documentation, or automatically installed.

**Comment by ChangWeiTan** [comment]
Hi Daniel, 

Thank you for your feedback. I have made the changes. Please have a look and let me know if there is anything else to improve. 

Cheers. 
Chang Wei

**Comment by lemire** [comment]
The revised README is more than good enough. Closing.
