### ISSUE TITLE
some suggests

### ISSUE THREAD

**Issue by xiaolongwu0713** [ChangWeiTan/TSRegression#4]

**Comment by xiaolongwu0713** [comment]
Hi,
Please specify the input dimension and meaning of each axis for the regressor. It's not user-friendly.

**Comment by ChangWeiTan** [comment]
Hi, please check my latest update. I have added some descriptions to the docstring for the regressors. Generally, all of the time series regressors take in inputs of (examples, timestep, channels). The classical regressors take in (examples, num_features) where in this work, the num_features are just the time series points.  Let me know if this is still not clear. Thank you
