### ISSUE TITLE
[Solved] Encoding ISO-8859-1 was needed to read BIDMC datasets

### ISSUE THREAD

**Issue by Didayolo** [ChangWeiTan/TSRegression#8]
When trying to read "BIDMC32RR", "BIDMC32HR", "BIDMC32SpO2" datasets, I got the following error:

```
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x96 in position 1164: invalid start byte
```

In order to solve it I had to make a change in `utils/data_loader.py` at line 80:

```Python
with open(full_file_path_and_name, 'r', encoding='ISO-8859-1') as file: # NEW
# with open(full_file_path_and_name, 'r', encoding='utf-8') as file: # OLD
```

I am not sure if the problem is general or came from my system settings. Still seems interesting to share.

**Comment by ChangWeiTan** [comment]
That is interesting. I never had that issue. Thanks for pointing this out.

**Comment by javierdjas** [comment]
I had the same issue, it solved it, thank you
